server:
  port: 8080

spring:
  datasource:
    username: root
    password: asuzncmi666
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.volochek.life
      name: Volochek Life
    - url: https://www.radiomv.ru
      name: Radio MV
    - url: https://www.ipfran.ru
      name: IP Fran
    - url: https://www.dimonvideo.ru
      name: Dimon Video
    - url: https://www.nikoartgallery.com
      name: Niko Art Gallery
    - url: https://www.et-cetera.ru/mobile
      name: Et Cetera Mobile
    - url: https://www.lutherancathedral.ru
      name: Lutheran Cathedral
    - url: https://www.dombulgakova.ru
      name: Dom Bulgakova
    - url: https://www.svetlovka.ru
      name: Svetlovka
